apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sokos-op-fasade
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: sokos-op-fasade-alerts
      rules:
        - alert: Applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="sokos-op-fasade"} == 0
          for: 5m
          annotations:
            action: "`kubectl describe pod {{ $labels.deployment }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l {{ $labels.deployment }} -n {{ $labels.namespace }}` for logger"
            summary: "App {{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: danger
            sokos_op_fasade_type: sokos-op-fasade
            alert_type: custom


---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sokos-op-fasade-slack
  namespace: okonomi
  labels:
    alertmanagerConfig: sokos-op-fasade-slack
spec:
  receivers:
    - name: sokos-op-fasade-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-mob-alerts-prod'
          iconEmoji: ':alert:'
          username: 'Alert prod-gcp'
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sokos_op_fasade_type"
        matchType: "="
        value: "sokos-op-fasade"
    groupInterval: 10s
    groupWait: 5s
    receiver: sokos-op-fasade-receiver
    repeatInterval: 2m
