apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-op-fasade
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  ingresses:
    - "https://okonomiportalen.intern.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  env:
  - name: SOKOS_MIKROFRONTEND_API
    value: http://sokos-mikrofrontend-api
  - name: SOKOS_MIKROFRONTEND_API_SCOPE
    value: api://dev-gcp.okonomi.sokos-mikrofrontend-api/.default
  - name: SOKOS_MIKROFRONTEND_PATH
    value: "/mikrofrontend-api"
