apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-op-fasade
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /okonomiportalen/internal/isAlive
    initialDelay: 10
  readiness:
    path: /okonomiportalen/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        claims:
          groups:
            - id: "0155880b-f708-4f61-ade8-00931fe41b89" # 0000-GA-SOKOS-CHAPPAI
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      rules:
        - application: sokos-mikrofrontend-api
  ingresses:
    - "https://okonomiportalen.intern.dev.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  env:
  - name: SOKOS_MIKROFRONTEND_API
    value: http://sokos-mikrofrontend-api
  - name: SOKOS_MIKROFRONTEND_API_SCOPE
    value: api://dev-gcp.okonomi.sokos-mikrofrontend-api/.default
  - name: SOKOS_MIKROFRONTEND_PATH
    value: "/mikrofrontend-api"