apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-op-fasade
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /okonomiportalen/internal/isAlive
    initialDelay: 10
  readiness:
    path: /okonomiportalen/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      rules:
        - application: sokos-mikrofrontend-api
  ingresses:
    - "https://okonomiportalen.intern.dev.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  env:
  - name: SERVER_BASE_PATH
    value: "/okonomiportalen"
  - name: SERVER_PORT
    value: "8080"
    
  - name: SOKOS_MIKROFRONTEND_API_URL
    value: http://sokos-mikrofrontend-api
