apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-op-fasade-manuell
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://okonomiportalen-manuell.intern.dev.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
    env:
      - name: SOKOS_MIKROFRONTEND_API_URL
        value: https://sokos-mikrofrontend-api.intern.dev.nav.no
