apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-op-fasade
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{ image }}
  port: 7100
  liveness:
    path: /okonomiportalen/internal/isAlive
    initialDelay: 10
  readiness:
    path: /okonomiportalen/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLoginIgnorePaths:
        - /internal/*
  ingresses:
    - "https://okonomiportalen.intern.dev.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
