apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-okonomiportalen-frontend
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{version}}
  port: 7100
  liveness:
    path: /sokos-okonomiportalen-frontend/internal/isAlive
    initialDelay: 10
  readiness:
    path: /sokos-okonomiportalen-frontend/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://okonomiportalen.dev.intern.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
