name: Manuell deploy
run-name: Deploy branch ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}-manuell
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bygg-og-push-docker-image:
    name: Bygg/test og push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache klient node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Cache server node_modules
        id: cache-server-node-modules
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('server/package-lock.json') }}

      - name: Installerer dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Installerer dependencies for server
        if: steps.cache-server-node-modules.outputs.cache-hit != 'true'
        run: cd server && npm install

      - name: Bygger applikasjonen
        run: npm run build

      - name: Bygg og publiser Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-manuell-dev-gcp:
    name: Deploy manuell til dev-gcp
    needs: [ bygg-og-push-docker-image ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/manual-dev-nais.yaml
