name: Manuell deploy til dev
run-name: Deploy branch ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
   bygg-push-deploy:
    permissions:
      contents: "read"
      id-token: "write"
    name: Bygg og push Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache klient node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Cache server node_modules
        id: cache-server-node-modules
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('server/package-lock.json') }}

      - name: Installerer dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Installerer dependencies for server
        if: steps.cache-server-node-modules.outputs.cache-hit != 'true'
        run: cd server && npm install

      - name: Bygger applikasjonen
        run: npm run build

      - name: Push docker image til Google Artifact Registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: okonomi
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: manuell
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

   deploy-manuell-dev-gcp:
     name: Deploy manuelt til dev-gcp
     needs: bygg-push-deploy
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: nais/deploy/actions/deploy@v1
         env:
           APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
           CLUSTER: dev-gcp
           IMAGE: ${{ needs.bygg-push-deploy.outputs.image }}
           RESOURCE: .nais/naiserator-dev.yaml
